version: '3.8'
services:
  app:
    build: 
      context: .
      target: builder
    ports:
      - "5173:5173"
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=lobby_db
      - POSTGRES_USER=lobby_user
      - POSTGRES_PASSWORD=lobby_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./lobby_data.sql:/docker-entrypoint-initdb.d/lobby_data.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data: